jenkins_base_dir: /data/jenkins

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'

plugins:
  - github.hpi
  - git.hpi
  - credentials.jpi
  - scm-api.hpi
  - matrix-project.jpi
  - git-client.hpi
  - github-api.hpi

jenkins_jobs: [
  { src: "build.xml.j2", dest: "books-service", app: "books-service" },
  { src: "build.xml.j2", dest: "books-fe", app: "books-fe" },
  { src: "build_test.xml.j2", dest: "books-service-test", app: "books-service" }
# no jenkins job to test front-end yet  { src: "build_test.xml.j2", dest: "books-fe-test", app: "books-fe" }
]